### ISSUE TITLE
Can I use this instead of certificate pinning?

### ISSUE THREAD

**Issue by matheuslc** [mberhault/go-sct#2]
Awesome work with this library, I learnt a lot with it. 

But studying more certificate transparency I get with this question. If I can use certificate transparency to avoid man in the middle attacks validating the SCT against the public log it would be nice!

**Comment by mberhault** [comment]
Certificate (or public key) pinning is more or less obsolete at this point (and HTTP public key pinning is officially deprecated), although nothing stops you from implementing it in your own application. It has been largely replaced by certificate transparency (you can find lots of good discussions using a simple "certificate pinning vs certificate transparency" websearch).

Validating SCTs properly (which is not a simple task) can provide protection against MITM attacks by ensuring that the certificate is recorded in at least one (preferably more) trusted CT log. If the SCT is found, you are now relying on log monitors to catch any misbehaving CA that has been found to issue certificates they shouldn't have.

You can yourself query certificates found in the logs for your (or any) domain through sites such as https://crt.sh/

Arguably, this is less absolute than public key pinning since it relies on detection of a fraudulent certificate **after** it was issued and possibly used. By comparison, public key pinning will reject any certificate signed by someone else.

Which to use is up to you, public key pinning may very well be suitable for your application, just be aware of some of its downsides.

**Comment by matheuslc** [comment]
Awesome. Thanks for shedding light on it.
